name: Deploy Twilio Serverless

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy-functions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download template env file (if exists)
        uses: actions/download-artifact@v3
        with:
          name: templates-env
          path: mercado-pago-serverless
        continue-on-error: true

      - name: Add base environment values
        run: |
          ENV_FILE=mercado-pago-serverless/.env
          echo "ACCOUNT_SID=${{ secrets.ACCOUNT_SID }}" >> $ENV_FILE
          echo "AUTH_TOKEN=${{ secrets.AUTH_TOKEN }}" >> $ENV_FILE
          echo "MERCADO_PAGO_ACCESS_TOKEN=${{ secrets.MERCADO_PAGO_ACCESS_TOKEN }}" >> $ENV_FILE
          echo "WHATSAPP_FROM_NUMBER=${{ secrets.WHATSAPP_FROM_NUMBER }}" >> $ENV_FILE

      - name: Install Twilio CLI
        run: |
          npm install -g twilio-cli
          twilio plugins:install @twilio-labs/plugin-serverless
          twilio config:set account-sid=${{ secrets.ACCOUNT_SID }}
          twilio config:set auth-token=${{ secrets.AUTH_TOKEN }}

      - name: Deploy Serverless Functions
        working-directory: mercado-pago-serverless
        run: |
          twilio serverless:deploy \
            --env .env \
            --service-name mercado-pago-serverless \
            --force
